import {
  Wrench,
  Zap,
  Droplet,
  Sparkles,
} from "lucide-react";

export const allServices = [
  {
    title: "Building Maintenance",
    description: "Complete building upkeep, repairs, and preventive maintenance.",
    icon: Wrench,
    features: ["Preventive Maintenance", "Emergency Repairs", "Regular Inspections"],
    href: "/services/maintenance",
    category: "all",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800",
  },
  {
    title: "Electrical Services",
    description: "Professional electrical installation and repair by certified electricians.",
    icon: Zap,
    features: ["Wiring & Rewiring", "Panel Upgrades", "Lighting Installation"],
    href: "/services/electrical",
    category: "all",
    image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=800",
  },
  {
    title: "Plumbing Services",
    description: "Expert plumbing solutions for leaks and installations.",
    icon: Droplet,
    features: ["Leak Detection", "Pipe Installation", "Drain Cleaning"],
    href: "/services/plumbing",
    category: "all",
    image: "https://images.unsplash.com/photo-1620321023374-d1a68fbc720d?auto=format&fit=crop&w=800",
  },
  {
    title: "Welding Services",
    description: "Custom metal fabrication and welding for structural components.",
    icon: Sparkles,
    features: ["Structural Welding", "Metal Fabrication", "Gate Manufacturing"],
    href: "/services/welding",
    category: "all",
    image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=800",
  },
  {
    title: "Welding Services",
    description: "Custom metal fabrication and welding for structural components.",
    icon: Sparkles,
    features: ["Structural Welding", "Metal Fabrication", "Gate Manufacturing"],
    href: "/services/welding",
    category: "all",
    image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=800",
  },
  {
    title: "Welding Services",
    description: "Custom metal fabrication and welding for structural components.",
    icon: Sparkles,
    features: ["Structural Welding", "Metal Fabrication", "Gate Manufacturing"],
    href: "/services/welding",
    category: "all",
    image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=800",
  },
  {
    title: "Welding Services",
    description: "Custom metal fabrication and welding for structural components.",
    icon: Sparkles,
    features: ["Structural Welding", "Metal Fabrication", "Gate Manufacturing"],
    href: "/services/welding",
    category: "all",
    image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=800",
  },
  {
    title: "Welding Services",
    description: "Custom metal fabrication and welding for structural components.",
    icon: Sparkles,
    features: ["Structural Welding", "Metal Fabrication", "Gate Manufacturing"],
    href: "/services/welding",
    category: "all",
    image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=800",
  },
];
