export const testimonials = [
  {
    id: 1,
    name: "Ahmed Al Mansoori",
    role: "Property Manager",
    company: "Al Reem Island Towers",
    location: "Al Reem Island, Abu Dhabi",
    rating: 5,
    date: "January 2024",
    content: "Walid Building Services has been our maintenance partner for 3 years. Their 24/7 emergency response and DM-certified technicians have kept our 5 towers running smoothly. Exceptional reliability.",
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400",
    service: "Building Maintenance",
    project: "Annual Maintenance Contract"
  },
  {
    id: 2,
    name: "Sarah Johnson",
    role: "Hotel Director",
    company: "Luxury Beach Resort",
    location: "Saadiyat Island, Abu Dhabi",
    rating: 5,
    date: "December 2023",
    content: "The electrical upgrade project was completed 2 weeks ahead of schedule. Professional team, clean work, and excellent communication throughout. Highly recommended for commercial projects.",
    image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=400",
    service: "Electrical Services",
    project: "Hotel Renovation"
  },
  {
    id: 3,
    name: "Mohammed Al Qubaisi",
    role: "Villa Owner",
    company: "Private Residence",
    location: "Khalifa City A, Abu Dhabi",
    rating: 5,
    date: "November 2023",
    content: "Emergency plumbing repair at 2 AM on a weekend. They arrived within 45 minutes and fixed the issue professionally. Pricing was fair and transparent. True 24/7 service.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400",
    service: "Plumbing & Pipe Fitting",
    project: "Emergency Repair"
  },
  {
    id: 4,
    name: "Fatima Al Shamsi",
    role: "Office Manager",
    company: "Tech Startup Hub",
    location: "Al Maryah Island, Abu Dhabi",
    rating: 5,
    date: "October 2023",
    content: "Complete office fit-out with partitions, electrical, and HVAC. The team understood our tech startup needs and delivered a modern workspace on budget. DM-certified quality.",
    image: "https://images.unsplash.com/photo-1494790108755-2616b612b786?auto=format&fit=crop&w=400",
    service: "Partition & Interior",
    project: "Office Fit-Out"
  },
  {
    id: 5,
    name: "Rashid Al Nahyan",
    role: "Compound Manager",
    company: "MBZ Residential Compound",
    location: "Mohammed Bin Zayed City",
    rating: 5,
    date: "September 2023",
    content: "Installed custom parking shades for 50 cars. Withstood UAE summer heat and storms perfectly. The team was professional and cleaned up thoroughly after completion.",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400",
    service: "Parking Shade & Outdoor",
    project: "Compound Shade Installation"
  },
  {
    id: 6,
    name: "Elena Petrova",
    role: "Restaurant Owner",
    company: "Fine Dining Restaurant",
    location: "Yas Island, Abu Dhabi",
    rating: 5,
    date: "August 2023",
    content: "Kitchen plumbing and ventilation system installation for our new restaurant. Compliant with Abu Dhabi Civil Defense regulations. Efficient and professional service.",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=400",
    service: "Welding & Fabrication",
    project: "Commercial Kitchen Setup"
  },
];
